# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-28 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PgtIOU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgtIou', models.CharField(max_length=255, unique=True)),
                ('tgt', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionServiceTicket',
            fields=[
                ('service_ticket', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='service ticket')),
                ('session_key', models.CharField(max_length=40, verbose_name='session key')),
            ],
            options={
                'verbose_name': 'session service ticket',
                'verbose_name_plural': 'session service tickets',
                'db_table': 'django_cas_session_service_ticket',
            },
        ),
        migrations.CreateModel(
            name='Tgt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('tgt', models.CharField(max_length=255)),
            ],
        ),
    ]
